### ISSUE TITLE
Sync failed when VM has no tag

### ISSUE THREAD

**Issue by fjamal15** [banyansecurity/pybanyan#37]
fjamal15@Farazs-MBP ~ % banyan cloud-resource sync-aws ec2 us-east-2 

--> Getting list of AWS EC2 resources:
Traceback (most recent call last):
  File "/usr/local/bin/banyan", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/banyan/main.py", line 108, in main
    app.run()
  File "/usr/local/lib/python3.9/site-packages/cement/core/foundation.py", line 916, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.9/site-packages/cement/ext/ext_argparse.py", line 808, in _dispatch
    return func()
  File "/usr/local/lib/python3.9/site-packages/banyan/controllers/cloud_resource.py", line 241, in sync_aws
    instances += aws.list_ec2()
  File "/usr/local/lib/python3.9/site-packages/banyan/ext/iaas/aws.py", line 67, in list_ec2
    for tag in vm.tags:
TypeError: 'NoneType' object is not iterable

**Comment by tdesikan** [comment]
Thanks for reporting. Fixing all related issues in this PR:

https://github.com/banyansecurity/pybanyan/pull/38

**Comment by tdesikan** [comment]
fixed in 0.27.1
