### ISSUE TITLE
`--api-url` and `--refresh-token` don't do anything

### ISSUE THREAD

**Issue by huguesalary** [banyansecurity/pybanyan#48]
How to reproduce:

`banyan --api-url https://net.banyanops.com --refresh-token=deadbeef service-web list`

```
Traceback (most recent call last):
  File "/usr/local/bin/banyan", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/banyan/main.py", line 110, in main
    with MyApp() as app:
  File "/usr/local/lib/python3.7/site-packages/cement/core/foundation.py", line 1728, in __enter__
    self.setup()
  File "/usr/local/lib/python3.7/site-packages/cement/core/foundation.py", line 934, in setup
    for res in self.hook.run('post_setup', self):
  File "/usr/local/lib/python3.7/site-packages/cement/core/hook.py", line 169, in run
    res = hook[2](*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/banyan/main.py", line 33, in extend_client
    client = BanyanApiClient(api_url, refresh_token, debug=app.debug)
  File "/usr/local/lib/python3.7/site-packages/banyan/api/__init__.py", line 96, in __init__
    raise BanyanError("Refresh token must be set")
banyan.core.exc.BanyanError: Refresh token must be set
Exception ignored in: <function BanyanApiClient.__del__ at 0xffff7e8764d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/banyan/api/__init__.py", line 117, in __del__
    if self._http:
AttributeError: 'BanyanApiClient' object has no attribute '_http'
```

**Comment by tdesikan** [comment]
the latest version (0.29.0) shouldn't have this issue. we're using `api-key` instead of `refresh-token` but refresh tokens will still work

```
$ banyan --api-url=https://upnsan.bnntest.com --api-key=abc123 service-web list

Name              ID                                     Type    Enabled    Created              Last Updated
----------------  -------------------------------------  ------  ---------  -------------------  -------------------
ConnectorService  ConnectorService.managed-cl-edge1.bnn  WEB     True       2022-07-20 15:58:00  2022-07-20 15:58:00
at-tdupnsan-93    at-tdupnsan-93.managed-cl-edge1.bnn    WEB     True       2023-03-22 17:13:28  2023-03-22 17:13:28
```

**Comment by huguesalary** [comment]
Confirmed, this now works
