### ISSUE TITLE
`banyan policy list-attachments policy_name` does not work

### ISSUE THREAD

**Issue by huguesalary** [banyansecurity/pybanyan#55]
With `banyan -v`
```
API library and command-line interface for Banyan Security 0.29.0
Cement Framework 3.0.8
Python 3.9.16
Platform macOS-13.1-arm64-arm-64bit
```

`banyan policy list-attachments policy_name ` returns 
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/banyan", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/banyan/main.py", line 123, in main
    app.run()
  File "/opt/homebrew/lib/python3.9/site-packages/cement/core/foundation.py", line 957, in run
    return_val = self.controller._dispatch()
  File "/opt/homebrew/lib/python3.9/site-packages/cement/ext/ext_argparse.py", line 810, in _dispatch
    return func()
  File "/opt/homebrew/lib/python3.9/site-packages/banyan/controllers/policy.py", line 99, in list_attachments
    attachments = attach_api.list()
  File "/opt/homebrew/lib/python3.9/site-packages/banyan/api/attachment.py", line 12, in list
    return Attachment.Schema().load(response_json, many=True)
  File "/opt/homebrew/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 748, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/opt/homebrew/lib/python3.9/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {0: {'AttachedToType': ['Must be one of: service, saasapp.']}, 543: {'AttachedToType': ['Must be one of: service, saasapp.']}, 576: {'AttachedToType': ['Must be one of: service, saasapp.']}, 584: {'AttachedToType': ['Must be one of: service, saasapp.']}, 585: {'AttachedToType': ['Must be one of: service, saasapp.']}, 674: {'AttachedToType': ['Must be one of: service, saasapp.']}}
```

**Comment by tdesikan** [comment]
fixed in #58
