### ISSUE TITLE
`banyan netagent list` does not work

### ISSUE THREAD

**Issue by huguesalary** [banyansecurity/pybanyan#56]
With `banyan -v`
```
API library and command-line interface for Banyan Security 0.29.0
Cement Framework 3.0.8
Python 3.9.16
Platform macOS-13.1-arm64-arm-64bit
```

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/banyan", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/banyan/main.py", line 123, in main
    app.run()
  File "/opt/homebrew/lib/python3.9/site-packages/cement/core/foundation.py", line 957, in run
    return_val = self.controller._dispatch()
  File "/opt/homebrew/lib/python3.9/site-packages/cement/ext/ext_argparse.py", line 810, in _dispatch
    return func()
  File "/opt/homebrew/lib/python3.9/site-packages/banyan/controllers/netagent.py", line 37, in list
    shield_name = agent.cluster_name or clusters.find(str(agent.cluster_id)).name
  File "/opt/homebrew/lib/python3.9/site-packages/banyan/api/base.py", line 84, in find
    return self.__getitem__(obj)
  File "/opt/homebrew/lib/python3.9/site-packages/banyan/api/base.py", line 46, in __getitem__
    self._ensure_cache()
  File "/opt/homebrew/lib/python3.9/site-packages/banyan/api/base.py", line 61, in _ensure_cache
    self.list()
  File "/opt/homebrew/lib/python3.9/site-packages/banyan/api/shield.py", line 25, in list
    self._config = ShieldConfig.Schema().load(response_json)
  File "/opt/homebrew/lib/python3.9/site-packages/marshmallow_dataclass/__init__.py", line 748, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/opt/homebrew/lib/python3.9/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'ShieldLastActivitiesMap': defaultdict(<class 'dict'>, {'SOME_UUID_THAT_I_MANUALLY_REMOVED_FROM_THIS_OUTPUT': {'value': {'InsertTime': ['Not a valid datetime.']}}})}
```

**Comment by tdesikan** [comment]
fixed in #57 

but, please note that the `netagent` sub-command is deprecated and will be removed soon; use `access-tier` instead
